# Generated by Django 4.2.7 on 2023-11-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='name',
        ),
    ]
